### ISSUE TITLE
    camera.pixformat

### ISSUE THREAD

**Issue by davefes** [shariltumin/esp32-cam-micropython-2022#29]
I tried to upgrade from firmware-20221203 to firmwares-20230717 and got an error saying to choose camera.pixformat between 1 and 9.  Has the contents of the help.py file, which I can't find in the latest commit, changed since then?

Thanks.

**Comment by shariltumin** [comment]
Hi Dave, yes there are some changes in the settings. You can find the updated version [here](https://github.com/shariltumin/esp32-cam-micropython-2022/tree/main/firmwares-20230717/scripts). What is new is the inclusion of esp32-s3. Xiao board is tiny and not that expensive, a great potential for your project.

**Comment by davefes** [comment]
Thank you.
