### ISSUE TITLE
machine.reset() sometimes fails

### ISSUE THREAD

**Issue by davefes** [shariltumin/esp32-cam-micropython-2022#47]
Latest image on a ESP32 Generic.

When doing a machine.reset() sometimes get the following:

E (3070) camera: Camera probe failed with error 0x105(ESP_ERR_NOT_FOUND)
E (3070) camera: Camera Init Failed
E (3070) camera: Camera deinit Failed
E (4130) camera: Camera probe failed with error 0x105(ESP_ERR_NOT_FOUND)
E (4130) camera: Camera Init Failed
E (4130) camera: Quality Failed
E (4130) camera: Special Effect Failed

A power-on-reset clears this problem.  Any suggestions?

Thanks

**Comment by shariltumin** [comment]
Have you try ```camera.deinit()``` before calling ```machine.reset()``` ?

**Comment by davefes** [comment]
I will try that.  It is a random event.

I start every program with:
```py
# during development
if machine.reset_cause() == machine.SOFT_RESET:
    print('you got a SOFT_RESET, so do a machine.reset()')
    time.sleep(1)
    machine.reset()
```
and it fails here before any camera init happens. Ah, `import camera` has happened before this.

**Comment by davefes** [comment]
Putting `camera_deinit()`gives a `E (1070) camera: Camera deinit Failed` which is not surprising as the camera has not been initialised.  My original error appeared to go away.

If I `import camera` after my `SOFT_RESET` test everything works properly.

Thank you.
